-- INSERT INTO User ( ID, NAME) VALUES (1, 'Jerry');
-- INSERT INTO User ( ID, NAME) VALUES (2, 'Tom');
--
-- INSERT INTO Contact(ID, TYPE, VALUE, USER_ID)VALUES(1, 'PHONE', '13512345678', 1);
--
-- INSERT INTO MyGroup (ID, NAME) VALUES (1, '小组1');
-- INSERT INTO MyGroup (ID, NAME) VALUES (2, '小组2');
--
--
--
-- INSERT INTO User_Group(USER_ID, GROUP_ID)values(1,1);
-- INSERT INTO User_Group(USER_ID, GROUP_ID)values(1,2);
-- INSERT INTO User_Group(USER_ID, GROUP_ID)values(2,1);
--
-- INSERT INTO Inputs ( ID, BARCODE) VALUES (1, 'ITEM000001');
-- INSERT INTO Inputs ( ID, BARCODE) VALUES (2, 'ITEM000002');


-- INSERT INTO A_1_1 ( ID,NAME,B_ID) VALUES (1,"Tom",1);
-- INSERT INTO A_1_1 ( ID,NAME ,B_ID) VALUES (2,"Jerry",2);
-- INSERT INTO A_1_1 ( ID,NAME ) VALUES (3,"Anna");
--
-- INSERT INTO B_1_1 ( ID,NAME ) VALUES (1,"P1");
-- INSERT INTO B_1_1 ( ID,NAME ) VALUES (2,"P2");
--
--
-- INSERT INTO A_1_N ( ID,NAME ) VALUES (1,"Class1");
-- INSERT INTO A_1_N ( ID,NAME ) VALUES (2,"Class2");
--
-- INSERT INTO B_1_N ( ID,NAME,A_ID) VALUES (1,"Tom",1);
-- INSERT INTO B_1_N ( ID,NAME,A_ID) VALUES (2,"Jerry",1);
-- INSERT INTO B_1_N ( ID,NAME,A_ID) VALUES (3,"Anna",2);
-- INSERT INTO B_1_N ( ID,NAME) VALUES (4,"Niky");
--
--
-- INSERT INTO A_N_N ( ID,NAME ) VALUES (1,"Tom");
-- INSERT INTO A_N_N ( ID,NAME ) VALUES (2,"Jerry");
-- INSERT INTO A_N_N ( ID,NAME ) VALUES (3,"Anna");
--
-- INSERT INTO B_N_N ( ID,NAME ) VALUES (1,"Math");
-- INSERT INTO B_N_N ( ID,NAME ) VALUES (2,"English");
-- INSERT INTO B_N_N ( ID,NAME ) VALUES (3,"Chinese");
--
-- INSERT INTO R_N_N ( A_ID, B_ID) VALUES (1,1);
-- INSERT INTO R_N_N ( A_ID, B_ID) VALUES (2,1);
-- INSERT INTO R_N_N ( A_ID, B_ID) VALUES (1,2);
-- INSERT INTO R_N_N ( A_ID, B_ID) VALUES (2,2);
-- INSERT INTO R_N_N ( A_ID, B_ID) VALUES (3,2);


INSERT INTO AllItems( BARCODE,NAME,UNIT,PRICE) VALUES ("ITEM000000","可口可乐","瓶",3.00);
INSERT INTO AllItems( BARCODE,NAME,UNIT,PRICE) VALUES ("ITEM000001","雪碧","瓶",3.00);
INSERT INTO AllItems( BARCODE,NAME,UNIT,PRICE) VALUES ("ITEM000002","苹果","斤",5.50);
INSERT INTO AllItems( BARCODE,NAME,UNIT,PRICE) VALUES ("ITEM000003","荔枝","斤",15.00);
INSERT INTO AllItems( BARCODE,NAME,UNIT,PRICE) VALUES ("ITEM000004","电池","个",2.00);
INSERT INTO AllItems( BARCODE,NAME,UNIT,PRICE) VALUES ("ITEM000005","方便面","袋",4.50);


INSERT INTO Promotions ( ID,NAME ) VALUES (1,"BUY_TWO_GET_ONE_FREE");


INSERT INTO A_1_1 ( ID,NAME ) VALUES (3,"Anna");